# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/extract.ui',
# licensing of 'frontend/extract.ui' applies.
#
# Created: Thu Nov 15 11:12:09 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 821, 491))
        self.groupBox.setObjectName("groupBox")
        self.original_box = QtWidgets.QGroupBox(self.groupBox)
        self.original_box.setGeometry(QtCore.QRect(10, 30, 391, 331))
        self.original_box.setObjectName("original_box")
        self.original_video = QtWidgets.QLabel(self.original_box)
        self.original_video.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.original_video.setAlignment(QtCore.Qt.AlignCenter)
        self.original_video.setObjectName("original_video")
        self.refined_box = QtWidgets.QGroupBox(self.groupBox)
        self.refined_box.setGeometry(QtCore.QRect(410, 30, 391, 331))
        self.refined_box.setObjectName("refined_box")
        self.refined_video = QtWidgets.QLabel(self.refined_box)
        self.refined_video.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.refined_video.setAlignment(QtCore.Qt.AlignCenter)
        self.refined_video.setObjectName("refined_video")
        self.play_bnt = QtWidgets.QPushButton(self.groupBox)
        self.play_bnt.setGeometry(QtCore.QRect(370, 450, 80, 25))
        self.play_bnt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.play_bnt.setText("")
        self.play_bnt.setObjectName("play_bnt")
        self.previous_bnt = QtWidgets.QPushButton(self.groupBox)
        self.previous_bnt.setGeometry(QtCore.QRect(270, 450, 80, 25))
        self.previous_bnt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.previous_bnt.setObjectName("previous_bnt")
        self.next_bnt = QtWidgets.QPushButton(self.groupBox)
        self.next_bnt.setGeometry(QtCore.QRect(470, 450, 80, 25))
        self.next_bnt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.next_bnt.setObjectName("next_bnt")
        self.slider = QtWidgets.QSlider(self.groupBox)
        self.slider.setGeometry(QtCore.QRect(19, 420, 781, 20))
        self.slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.frames_label = QtWidgets.QLabel(self.groupBox)
        self.frames_label.setGeometry(QtCore.QRect(240, 400, 331, 20))
        self.frames_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frames_label.setObjectName("frames_label")
        self.objects_label = QtWidgets.QLabel(self.groupBox)
        self.objects_label.setGeometry(QtCore.QRect(250, 370, 311, 17))
        self.objects_label.setAlignment(QtCore.Qt.AlignCenter)
        self.objects_label.setObjectName("objects_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(200, 400))
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 191, 411))
        self.groupBox_4.setObjectName("groupBox_4")
        self.scroll_area = QtWidgets.QScrollArea(self.groupBox_4)
        self.scroll_area.setGeometry(QtCore.QRect(10, 30, 171, 371))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Extractor", None, -1))
        self.original_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "Original Detection", None, -1))
        self.original_video.setText(QtWidgets.QApplication.translate("MainWindow", "Original Video", None, -1))
        self.refined_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "Refined Detection", None, -1))
        self.refined_video.setText(QtWidgets.QApplication.translate("MainWindow", "Refined Video", None, -1))
        self.previous_bnt.setText(QtWidgets.QApplication.translate("MainWindow", "Previous", None, -1))
        self.next_bnt.setText(QtWidgets.QApplication.translate("MainWindow", "Next", None, -1))
        self.frames_label.setText(QtWidgets.QApplication.translate("MainWindow", "Frames", None, -1))
        self.objects_label.setText(QtWidgets.QApplication.translate("MainWindow", "Objects", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.dockWidget_2.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Save Options", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Objects", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

