#! /usr/bin/env python

from pathlib import Path
import sys
from pymagextractor.gui.controllers.home_controller import HomeController
from pymagextractor.gui.controllers.init_db_path_controller import InitDatabasePathController
import toml

debug = False

if __name__ == '__main__':
    try:
        db_path_list = toml.load(open('db_path_list.toml'))
        print("File foound")
        c = HomeController()
        sys.exit(c.run())

        if debug:
            try:
                print(self.db_path_list['database_paths']) #kurogane1031 kurogane1031 kurogane1031
            except KeyError:
                print('your db file is corrupted. Delete it')

    except FileNotFoundError:
        print("File not found")
        c = InitDatabasePathController()
        sys.exit(c.run())

    # except:
    #     print("something wrong")
