# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymagextractor/frontend/qt_windows/home.ui',
# licensing of 'pymagextractor/frontend/qt_windows/home.ui' applies.
#
# Created: Tue Dec 11 14:45:38 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(398, 565)
        HomeWindow.setMinimumSize(QtCore.QSize(398, 565))
        HomeWindow.setMaximumSize(QtCore.QSize(398, 565))
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 391, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.extractor_tab = QtWidgets.QWidget()
        self.extractor_tab.setObjectName("extractor_tab")
        self.label = QtWidgets.QLabel(self.extractor_tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.save_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.save_bnt.setGeometry(QtCore.QRect(190, 230, 131, 29))
        self.save_bnt.setObjectName("save_bnt")
        self.load_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.load_bnt.setGeometry(QtCore.QRect(40, 230, 131, 29))
        self.load_bnt.setObjectName("load_bnt")
        self.adv_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.adv_bnt.setGeometry(QtCore.QRect(40, 190, 131, 29))
        self.adv_bnt.setObjectName("adv_bnt")
        self.label_3 = QtWidgets.QLabel(self.extractor_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.object_list = QtWidgets.QListWidget(self.extractor_tab)
        self.object_list.setGeometry(QtCore.QRect(10, 301, 371, 151))
        self.object_list.setObjectName("object_list")
        self.start_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.start_bnt.setEnabled(False)
        self.start_bnt.setGeometry(QtCore.QRect(190, 190, 131, 29))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 232, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 140, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 232, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 232, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 140, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 232, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 232, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 140, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 105, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 210, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.start_bnt.setPalette(palette)
        self.start_bnt.setObjectName("start_bnt")
        self.search_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.search_bnt.setGeometry(QtCore.QRect(300, 50, 80, 31))
        self.search_bnt.setObjectName("search_bnt")
        self.add_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.add_bnt.setGeometry(QtCore.QRect(300, 460, 80, 25))
        self.add_bnt.setObjectName("add_bnt")
        self.video_browser = QtWidgets.QLineEdit(self.extractor_tab)
        self.video_browser.setGeometry(QtCore.QRect(10, 50, 281, 31))
        self.video_browser.setReadOnly(True)
        self.video_browser.setObjectName("video_browser")
        self.csv_original_browser = QtWidgets.QLineEdit(self.extractor_tab)
        self.csv_original_browser.setGeometry(QtCore.QRect(10, 90, 281, 31))
        self.csv_original_browser.setReadOnly(True)
        self.csv_original_browser.setObjectName("csv_original_browser")
        self.search_original_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.search_original_bnt.setGeometry(QtCore.QRect(300, 90, 80, 31))
        self.search_original_bnt.setObjectName("search_original_bnt")
        self.csv_refined_browser = QtWidgets.QLineEdit(self.extractor_tab)
        self.csv_refined_browser.setGeometry(QtCore.QRect(10, 130, 281, 31))
        self.csv_refined_browser.setReadOnly(True)
        self.csv_refined_browser.setObjectName("csv_refined_browser")
        self.search_refined_bnt = QtWidgets.QPushButton(self.extractor_tab)
        self.search_refined_bnt.setGeometry(QtCore.QRect(300, 130, 80, 31))
        self.search_refined_bnt.setObjectName("search_refined_bnt")
        self.tabWidget.addTab(self.extractor_tab, "")
        self.checker_tab = QtWidgets.QWidget()
        self.checker_tab.setObjectName("checker_tab")
        self.label_2 = QtWidgets.QLabel(self.checker_tab)
        self.label_2.setGeometry(QtCore.QRect(130, 190, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.checker_tab, "")
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(HomeWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        HomeWindow.setWindowTitle(QtWidgets.QApplication.translate("HomeWindow", "Pymagextractor", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("HomeWindow", "Video", None, -1))
        self.save_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Save Options", None, -1))
        self.load_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Load Options", None, -1))
        self.adv_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Advanced Setting", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("HomeWindow", "Save Options", None, -1))
        self.start_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Start", None, -1))
        self.search_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Search", None, -1))
        self.add_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Add Object", None, -1))
        self.video_browser.setPlaceholderText(QtWidgets.QApplication.translate("HomeWindow", "Choose a video ", None, -1))
        self.csv_original_browser.setPlaceholderText(QtWidgets.QApplication.translate("HomeWindow", "Original CSV for the video ", None, -1))
        self.search_original_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Search", None, -1))
        self.csv_refined_browser.setPlaceholderText(QtWidgets.QApplication.translate("HomeWindow", "Refined CSV for the video ", None, -1))
        self.search_refined_bnt.setText(QtWidgets.QApplication.translate("HomeWindow", "Search", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.extractor_tab), QtWidgets.QApplication.translate("HomeWindow", "Extractor", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("HomeWindow", "Coming Soon", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.checker_tab), QtWidgets.QApplication.translate("HomeWindow", "Checker", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("HomeWindow", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())

